In [ ]:
from __future__ import division
from statistics import mode
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import math
from scipy.spatial.distance import pdist, squareform
import numbers

### Reading data set

In [5]:
path = os.getcwd()
datasetpath = os.path.join(path,"data")
datasetpath = os.path.join(datasetpath,"2006.csv")
flights = pd.read_csv(datasetpath)
flights

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2006,1,11,3,743.0,745,1024.0,1018,US,343,...,45,13,0,NaN,0,0,0,0,0,0
1,2006,1,11,3,1053.0,1053,1313.0,1318,US,613,...,27,19,0,NaN,0,0,0,0,0,0
2,2006,1,11,3,1915.0,1915,2110.0,2133,US,617,...,4,11,0,NaN,0,0,0,0,0,0
3,2006,1,11,3,1753.0,1755,1925.0,1933,US,300,...,16,10,0,NaN,0,0,0,0,0,0
4,2006,1,11,3,824.0,832,1015.0,1015,US,765,...,27,12,0,NaN,0,0,0,0,0,0
5,2006,1,11,3,627.0,630,834.0,832,US,295,...,6,13,0,NaN,0,0,0,0,0,0
6,2006,1,11,3,825.0,820,1041.0,1021,US,349,...,4,21,0,NaN,0,0,0,20,0,0
7,2006,1,11,3,942.0,945,1155.0,1148,US,356,...,4,8,0,NaN,0,0,0,0,0,0
8,2006,1,11,3,1239.0,1245,1438.0,1445,US,775,...,4,12,0,NaN,0,0,0,0,0,0
9,2006,1,11,3,1642.0,1645,1841.0,1845,US,1002,...,4,10,0,NaN,0,0,0,0,0,0
10,2006,1,11,3,1836.0,1835,NaN,2035,US,1103,...,0,17,0,NaN,1,0,0,0,0,0
11,2006,1,11,3,NaN,1725,NaN,1845,US,69,...,0,0,1,A,0,0,0,0,0,0
12,2006,1,11,3,613.0,620,738.0,743,US,1159,...,4,12,0,NaN,0,0,0,0,0,0
13,2006,1,11,3,1125.0,1125,1242.0,1245,US,1249,...,3,6,0,NaN,0,0,0,0,0,0
14,2006,1,11,3,2045.0,2045,2205.0,2200,US,1680,...,14,8,0,NaN,0,0,0,0,0,0
15,2006,1,11,3,1342.0,1340,1509.0,1455,US,1681,...,4,10,0,NaN,0,0,0,0,0,0
16,2006,1,11,3,1752.0,1540,1923.0,1654,US,127,...,3,19,0,NaN,0,0,0,149,0,0
17,2006,1,11,3,724.0,730,843.0,845,US,277,...,17,8,0,NaN,0,0,0,0,0,0
18,2006,1,11,3,1153.0,1145,1324.0,1259,US,637,...,3,38,0,NaN,0,0,0,25,0,0
19,2006,1,11,3,528.0,525,640.0,640,US,1658,...,10,10,0,NaN,0,0,0,0,0,0
20,2006,1,11,3,630.0,630,950.0,1021,US,419,...,19,14,0,NaN,0,0,0,0,0,0
21,2006,1,11,3,1515.0,1520,1651.0,1650,US,1607,...,5,14,0,NaN,0,0,0,0,0,0
22,2006,1,11,3,557.0,605,805.0,818,US,78,...,5,11,0,NaN,0,0,0,0,0,0
23,2006,1,11,3,806.0,810,1035.0,1020,US,218,...,8,13,0,NaN,0,0,0,15,0,0
24,2006,1,11,3,1828.0,1830,2035.0,2041,US,918,...,6,9,0,NaN,0,0,0,0,0,0
25,2006,1,11,3,910.0,640,NaN,915,US,1650,...,0,12,0,NaN,1,0,0,0,0,0
26,2006,1,11,3,725.0,725,1015.0,1021,US,1636,...,9,9,0,NaN,0,0,0,0,0,0
27,2006,1,11,3,1555.0,1600,1751.0,1806,US,678,...,5,10,0,NaN,0,0,0,0,0,0
28,2006,1,11,3,657.0,700,902.0,905,US,856,...,6,20,0,NaN,0,0,0,0,0,0
29,2006,1,11,3,1056.0,1100,1329.0,1317,US,53,...,12,14,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7141892,2006,12,29,5,656.0,700,838.0,935,DL,1647,...,6,10,0,NaN,0,0,0,0,0,0
7141893,2006,12,29,5,1029.0,1033,1221.0,1209,DL,1647,...,10,30,0,NaN,0,0,0,0,0,0
7141894,2006,12,29,5,1325.0,1334,2118.0,2106,DL,1648,...,18,17,0,NaN,0,0,0,0,0,0
7141895,2006,12,29,5,2243.0,2245,25.0,27,DL,1648,...,4,14,0,NaN,0,0,0,0,0,0
7141896,2006,12,29,5,1652.0,1657,1958.0,1956,DL,1649,...,9,17,0,NaN,0,0,0,0,0,0
7141897,2006,12,29,5,2135.0,2140,2240.0,2257,DL,1650,...,5,19,0,NaN,0,0,0,0,0,0
7141898,2006,12,29,5,2005.0,1840,NaN,1959,DL,1651,...,0,22,0,NaN,1,0,0,0,0,0
7141899,2006,12,29,5,704.0,705,910.0,906,DL,1653,...,19,15,0,NaN,0,0,0,0,0,0
7141900,2006,12,29,5,956.0,1001,1244.0,1255,DL,1654,...,6,11,0,NaN,0,0,0,0,0,0
7141901,2006,12,29,5,1352.0,1356,1444.0,1453,DL,1654,...,4,11,0,NaN,0,0,0,0,0,0
7141902,2006,12,29,5,700.0,700,1017.0,1005,DL,1655,...,23,19,0,NaN,0,0,0,0,0,0
7141903,2006,12,29,5,1115.0,1100,1242.0,1231,DL,1655,...,6,22,0,NaN,0,0,0,0,0,0
7141904,2006,12,29,5,2010.0,2010,11.0,2345,DL,1656,...,5,86,0,NaN,0,0,0,26,0,0
7141905,2006,12,29,5,1158.0,1205,1305.0,1311,DL,1657,...,5,11,0,NaN,0,0,0,0,0,0
7141906,2006,12,29,5,1846.0,1818,2037.0,2012,DL,1658,...,12,14,0,NaN,0,0,0,0,0,25
7141907,2006,12,29,5,2122.0,2105,2317.0,2244,DL,1658,...,65,11,0,NaN,0,17,0,16,0,0
7141908,2006,12,29,5,2258.0,2300,641.0,613,DL,1660,...,6,13,0,NaN,0,0,0,28,0,0
7141909,2006,12,29,5,805.0,810,1020.0,1007,DL,1663,...,14,20,0,NaN,0,0,0,0,0,0
7141910,2006,12,29,5,1138.0,1130,1404.0,1400,DL,1663,...,5,18,0,NaN,0,0,0,0,0,0
7141911,2006,12,29,5,1803.0,1804,2023.0,2019,DL,1669,...,17,20,0,NaN,0,0,0,0,0,0
7141912,2006,12,29,5,1511.0,1514,1702.0,1715,DL,1670,...,8,13,0,NaN,0,0,0,0,0,0
7141913,2006,12,29,5,1314.0,1322,2223.0,2156,DL,1671,...,35,23,0,NaN,0,0,0,27,0,0
7141914,2006,12,29,5,1950.0,1940,2234.0,2234,DL,1672,...,7,14,0,NaN,0,0,0,0,0,0
7141915,2006,12,29,5,1726.0,1730,1854.0,1859,DL,1673,...,10,10,0,NaN,0,0,0,0,0,0
7141916,2006,12,29,5,1151.0,1156,1706.0,1659,DL,1674,...,25,15,0,NaN,0,0,0,0,0,0
7141917,2006,12,29,5,1246.0,1249,1452.0,1459,DL,1675,...,6,12,0,NaN,0,0,0,0,0,0
7141918,2006,12,29,5,1225.0,1155,2033.0,1931,DL,1676,...,12,35,0,NaN,0,30,0,32,0,0
7141919,2006,12,29,5,2118.0,2115,2254.0,2241,DL,1676,...,9,27,0,NaN,0,0,0,0,0,0
7141920,2006,12,29,5,2122.0,2127,2209.0,2223,DL,1677,...,5,21,0,NaN,0,0,0,0,0,0
7141921,2006,12,29,5,2042.0,2045,2213.0,2235,DL,1678,...,5,15,0,NaN,0,0,0,0,0,0

In [ ]:
l = flights.columns[flights.isnull().any()].tolist()
l

In [ ]:
from collections import Counter
for col in l:
    print(Counter(np.array(flights[col])))

In [17]:
flights.iloc[1]

Year                   2006
Month                     1
DayofMonth               11
DayOfWeek                 3
DepTime                1053
CRSDepTime             1053
ArrTime                1313
CRSArrTime             1318
UniqueCarrier            US
FlightNum               613
TailNum              N834AW
ActualElapsedTime       260
CRSElapsedTime          265
AirTime                 214
ArrDelay                 -5
DepDelay                  0
Origin                  ATL
Dest                    PHX
Distance               1587
TaxiIn                   27
TaxiOut                  19
Cancelled                 0
CancellationCode        NaN
Diverted                  0
CarrierDelay              0
WeatherDelay              0
NASDelay                  0
SecurityDelay             0
LateAircraftDelay         0
Name: 1, dtype: object

In [ ]:
print(1)